### ISSUE TITLE
Need to update section classes

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/radix_layouts#3]
Hi @arshad hope youre still around. THe section class names were changed in core (added an "l-" prefix), and I'm thinking it would be good to update Radix to match. Example `class = "header"` is now `class="l-header"`

**Comment by docwilmot** [comment]
It would also be nice to update the icons to show the header and footer regions. Fooled me again this morning.

**Comment by shadcn** [comment]
Yep. Adding this to my todo list. Adding the classes should be easy. Updating icons might take a while. I've zero skills in design :)

**Comment by docwilmot** [comment]
Core layout icons are 50x75, while yours are 50x64. If you make a 50x75 template in Photoshop etc with a top layer with a purple bar top and bottom, and just import the exisiting icons into the background of that template and hit save, youd get something like this. Would this be sufficient? 

![radix-brown](https://cloud.githubusercontent.com/assets/1042283/8107468/fda86b16-100e-11e5-8516-b9f361099c35.png)

**Comment by shadcn** [comment]
Yeah this looks good.
