### ISSUE TITLE
Proposal to remove width restrictions 

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/radix_layouts#5]
Hi @arshad 

I've just spent a while working with themes, and wanted to get your opinion as the leading layout creator so far.

If layouts have widths assigned and themes also at the same time, it is confusing. Imagine a new Backdrop user installing a new layout which sets 1024px and a theme which sets 960px at the same time. That would be confusion, to me.

I propose that for the sake of better UX we try and set a standard, and allow only either themes or layouts to restrict widths. Considering that the core themes have fixed widths, and the core layouts do not, I am proposing to keep this standard. 

I think if you support this with your bunch of layouts, it would probably set a precedent. What do you think?

**Comment by klonos** [comment]
I think that conceptually this make perfect sense. Themes should control the width.

**Comment by docwilmot** [comment]
@arshad any thoughts on this?

A bit of discussion happened in this issue: https://github.com/backdrop/backdrop-issues/issues/698#issuecomment-75434782 so I'll continue there. Feel free to close this.

**Comment by jenlampton** [comment]
Since core layouts now have widths, I'm assuming keeping the widths in contrib layouts makes sense now? I'm going to close this issue, but if that's not the case, please re-open.
